version: '3'
services:
  dokuwiki:
    image: shuosc/dokuwiki:latest
    ports:
      - 8081:80
    # environment:
    #   - DIR=wiki
    volumes:
      - ./data:/opt/data
      - ./log:/var/log/apache2