name: ci

on:
  push:
    tags:
      - v*

env:
  APP_NAME: dokuwiki
  DOCKERHUB_REPO: shuosc/dokuwiki

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v5
            linux/arm/v7
            linux/arm64
            linux/mips64le
            linux/ppc64le
            linux/s390x
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
      -
        name: Login to Alibaba Cloud Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACE_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Push Images to ACR
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
          dst: |
            registry.cn-shanghai.aliyuncs.com/${{ env.DOCKERHUB_REPO }}:latest
            registry.cn-shanghai.aliyuncs.com/${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
